name: pushover-actions

on: push

jobs:
  pushover-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # required to clone your code
      - name: pushover-actions
        uses: spookfish/pushover-actions@master
        with:
          token: ${{ secrets.PUSHOVER_TOKEN }}
          user: ${{ secrets.PUSHOVER_USER }}
          message: 'from github workflow with love'
