on: push
jobs:
  pushover-job:
    name: Pushover Notification
    runs-on: ubuntu-latest
    steps:
    - name: send pushover message
      uses: actions/checkout@1.0.2
      with:
        token: ${{ secrets.PUSHOVER_TOKEN }}
        user: ${{ secrets.PUSHOVER_USER }}
        message: 'from github workflow with love'
