on: push
jobs:
  pushover-job:
    name: Pushover Notification
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Send Pushover Message
      uses: ./
      with:
        token: ${{ secrets.PUSHOVER_TOKEN }}
        user: ${{ secrets.PUSHOVER_USER }}
        message: 'from github workflow with love'
